// @vitest-environment happy-dom

import {
  act,
  cleanup,
  fireEvent,
  render,
  screen,
} from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import InspectableImage from "../../src/components/InspectableImage";
import {
  invokeCalls,
  mockCommands,
  resetTauriMocks,
} from "../mocks/tauri";

beforeEach(() => {
  resetTauriMocks();
  mockCommands({
    log_event: () => null,
    record_recent_notification: () => ({}),
  });
  vi.useFakeTimers();
});

afterEach(() => {
  cleanup();
  vi.useRealTimers();
});

describe("momentary original-pixel inspection", () => {
  it("does not enlarge the fitted image when the setting is off", () => {
    render(
      <InspectableImage
        hash="photo-hash"
        fileName="family.jpg"
        enlargeSmall={false}
        sourceWidth={640}
        sourceHeight={480}
      />,
    );

    const image = screen.getByAltText("family.jpg");
    expect(image.className).toContain("h-full w-full");
    expect(image.getAttribute("style")).toContain("max-width: 640px");
    expect(image.getAttribute("style")).toContain("max-height: 480px");
  });

  it("starts only after the hold threshold and returns on release", () => {
    render(
      <InspectableImage hash="photo-hash" fileName="family.jpg" enlargeSmall />,
    );
    const viewport = screen.getByTitle("Press and hold for original pixels");

    fireEvent.pointerDown(viewport, {
      pointerId: 1,
      button: 0,
      isPrimary: true,
      clientX: 20,
      clientY: 30,
    });
    act(() => vi.advanceTimersByTime(134));
    expect(screen.queryByAltText("family.jpg at original size")).toBeNull();

    act(() => vi.advanceTimersByTime(1));
    expect(screen.getByAltText("family.jpg at original size")).toBeTruthy();

    fireEvent.pointerUp(window, { pointerId: 1, clientX: 30, clientY: 40 });
    expect(screen.queryByAltText("family.jpg at original size")).toBeNull();
  });

  it("suppresses the click generated by a completed hold", () => {
    const activate = vi.fn();
    render(
      <div onClick={activate}>
        <InspectableImage
          hash="photo-hash"
          fileName="family.jpg"
          enlargeSmall
        />
      </div>,
    );
    const viewport = screen.getByTitle("Press and hold for original pixels");
    fireEvent.pointerDown(viewport, {
      pointerId: 2,
      button: 0,
      isPrimary: true,
    });
    act(() => vi.advanceTimersByTime(135));
    fireEvent.pointerUp(window, { pointerId: 2 });
    fireEvent.click(viewport, { detail: 1 });

    expect(activate).not.toHaveBeenCalled();
  });

  it("cancels immediately on window blur", () => {
    render(
      <InspectableImage hash="photo-hash" fileName="family.jpg" enlargeSmall />,
    );
    const viewport = screen.getByTitle("Press and hold for original pixels");
    fireEvent.pointerDown(viewport, {
      pointerId: 3,
      button: 0,
      isPrimary: true,
    });
    act(() => vi.advanceTimersByTime(135));
    expect(screen.getByAltText("family.jpg at original size")).toBeTruthy();

    fireEvent.blur(window);

    expect(screen.queryByAltText("family.jpg at original size")).toBeNull();
  });

  it("shows a readable result when the original cannot be decoded", () => {
    render(
      <InspectableImage hash="photo-hash" fileName="family.jpg" enlargeSmall />,
    );
    const viewport = screen.getByTitle("Press and hold for original pixels");
    fireEvent.pointerDown(viewport, {
      pointerId: 5,
      button: 0,
      isPrimary: true,
    });
    act(() => vi.advanceTimersByTime(135));

    fireEvent.error(screen.getByAltText("family.jpg at original size"));
    fireEvent.pointerUp(window, { pointerId: 5 });

    expect(screen.queryByText("Original pixels unavailable.")).toBeNull();
    expect(screen.getByRole("alert").textContent).toContain(
      "Couldn’t show the original pixels for family.jpg.",
    );
    expect(
      invokeCalls.some((call) => call.command === "record_recent_notification"),
    ).toBe(true);
    expect(
      invokeCalls.some((call) => call.command === "publish_notification"),
    ).toBe(false);
  });
});
